program animation_script
   implicit none

   integer :: counter, counter_end
   character(len=*), parameter :: base = "./data/temp."
   character(len=4) :: serial_num

   counter_end = 50

   print *, "#"
   print *, "# gnuplot script generated by animation_script.f90"
   print *, "#"
   print *, " "
   print *, "set xlabel 'x'              # x-axis"
   print *, "set ylabel 'temperature'    # y-axis"
   print *, "set xrange[-1.0:1.0]     # j-grid min & max"
   print *, "set yrange[0.0:1.0]         # temperature min & max"
   print *, "set grid"
   print *, "set xlabel font 'Arial,20' "
   print *, "set ylabel font 'Arial,20' "
   print *, "set tics font 'Arial,20'"
   print *, "set key off"

   do counter = 0, counter_end
      write(serial_num,'(i4.4)') counter
      print *, "plot '"//trim(base)//serial_num//"' w lp"
      if (counter == 0) then
         print *, "pause 2"
      else
         print *, "pause 0.2"
      end if
   end do

   print *, "pause -1"
end program animation_script
